### ISSUE TITLE
Really good API

### ISSUE THREAD

**Issue by bryanrafaelbueno** [MushroomMif/aoh3-fabric-api#1]
Good job man, i got it working fine, thanks!

**Comment by MushroomMif** [comment]
Thank you, I'm glad it works!

**Comment by bryanrafaelbueno** [comment]
Do you know if I can add UI elements on main menu using this? I tried but the function that are the MainMenu isn't void

**Comment by MushroomMif** [comment]
> Do you know if I can add UI elements on main menu using this? I tried but the function that are the MainMenu isn't void

Yeah, you can definitely do it. Inject to the `MainMenu` class constructor using the [Mixin library](https://github.com/SpongePowered/Mixin) and add your UI element to `menuElements` list there

**Comment by bryanrafaelbueno** [comment]
Yeah but, i got this error: 'menuElements' has private access in 'aoc. kingdoms. lukasz. menu. Menu'
![image](https://github.com/user-attachments/assets/8336fb39-886e-429d-a464-441f318572d1)

**Comment by bryanrafaelbueno** [comment]
Do you have discord? To talk about that

**Comment by MushroomMif** [comment]
> Yeah but, i got this error: 'menuElements' has private access in 'aoc. kingdoms. lukasz. menu. Menu' ![image](https://private-user-images.githubusercontent.com/85371842/384721283-8336fb39-886e-429d-a464-441f318572d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNzk2MzksIm5iZiI6MTczMTI3OTMzOSwicGF0aCI6Ii84NTM3MTg0Mi8zODQ3MjEyODMtODMzNmZiMzktODg2ZS00MjlkLWE0NjQtNDQxZjMxODU3MmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDIyNTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMmM5NDJiNmQ4MWFiMTg1NjQ0ZDYyMzRjN2RkNzc2MzQ4ZDM1YjZiMThmNTk5MmNhOTdlZDY5NmRjMWY5YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._qNTSVAldBJY1ZroHdB0R_cafhXaypNd-QV17tiUsMU)

This is a different menuElements list, you can obtain the right one using [Local](https://github.com/LlamaLad7/MixinExtras/wiki/Local) annotation from MixinExtras while injecting before initMenu method call in MainMenu constructor

**Comment by MushroomMif** [comment]
> Do you have discord? To talk about that

Yeah, my username there is mushroommif

**Comment by bryanrafaelbueno** [comment]
I sent a friend request
